package com.johnymoo.arverify.export

import java.util.Locale

/** Serializes an ARCore point cloud (x,y,z,confidence per point) to ASCII PLY. */
object PlyWriter {
    /**
     * @param points flat array of 4 floats per point: x, y, z, confidence.
     *               A trailing partial group (size not a multiple of 4) is ignored.
     */
    fun toAsciiPly(points: FloatArray): String {
        val count = points.size / 4
        return buildString {
            append("ply\n")
            append("format ascii 1.0\n")
            append("comment Generated by ARCoreVerify\n")
            append("element vertex ").append(count).append('\n')
            append("property float x\n")
            append("property float y\n")
            append("property float z\n")
            append("property float confidence\n")
            append("end_header\n")
            for (i in 0 until count) {
                val o = i * 4
                append(
                    String.format(
                        Locale.US, "%.6f %.6f %.6f %.6f\n",
                        points[o], points[o + 1], points[o + 2], points[o + 3]
                    )
                )
            }
        }
    }
}
